Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./bombsquad_server", line 136, in run
    l = sys.stdin.readline()
IOError: [Errno 9] Bad file descriptor

Requesting shared-playlist 242855...
Playlist 'server' (teams) downloaded; running...
BombSquad headless 1.4.150 (14369) entering server-mode Mon Mar 30 19:30:08 2020
UDP port 43210 access check successful. Your server appears to be joinable from the internet.
